version: "3"

services:
  client:
    container_name: exchange_client
    build:
      context: ./exchange-client
      dockerfile: Dockerfile
    volumes:
      - ./:/exchange-client
    ports:
      - "80:5173"
  postgre:
    container_name: exchange_postgre
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword123
      POSTGRES_DB: node-exchange
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  pgadmin:
    container_name: exchange_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    depends_on:
      - postgre
